on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_app:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant gradlew permissions execution
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      
    
      
